routes/web.php
<?php

use App\Http\Controllers\PackageController;
use App\Http\Controllers\ProjectController;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return redirect()->route('project.index');
});

Route::resource('project', ProjectController::class);
Route::resource('package', PackageController::class);

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Package;
use DateTime;

class Project extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'costs', 'scope', 'quality', 'benefit', 'risk', 'groups', 'status', 'deadline'];

    public function getProgress(){
        $allPackages = $this->packages()->count();
        if($allPackages == 0){ return 0; }
        $donePackages = $this->packages()->where('status', 'Fertig')->count();
        return round($donePackages / $allPackages, 2)*100;
    }

    public function packages(){
        return $this->hasMany(Package::class);
    }

    public function getStatusColor(Project $project){
        switch($project->status){
            case('Offen'): return 'black'; break;
            case('Fertig'): return 'green-600'; break;
            case('Abgebrochen'): return 'gray-600'; break;
        }
    }

    public function formatDeadline(){
        return (new DateTime($this->deadline))->format('d.m.Y');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('project.index')
            ->with('projects', Project::orderBy('status', 'DESC')->orderBy('deadline', 'ASC')->get());
    }
#    sortBy('deadline')->sortByDesc('status')
    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'costs' => 'required',
            'scope' => 'required',
            'quality' => 'required',
            'benefit' => 'required',
            'risk' => 'required',
            'groups' => 'nullable',
            'status' => 'nullable',
            'deadline' => 'required|date'
        ]);

        if($validator->fails()){
            redirect()->route('project.index')->withErrors($validator)->with('createProject', true);
        }

        Project::create($validator->validated());

        return redirect()->route('project.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Project $project)
    {
        return view('project.show')
            ->with('project', $project)
            ->with('packages', $project->packages()->orderBy('status', 'DESC')->orderBy('deadline', 'ASC')->get());
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Project $project)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'costs' => 'required',
            'scope' => 'required',
            'quality' => 'required',
            'benefit' => 'required',
            'risk' => 'required',
            'groups' => 'nullable',
            'status' => 'nullable',
            'deadline' => 'required|date'
        ]);

        if($validator->fails()){
            redirect()->route('project.show', [$project])->withErrors($validator)->with('editProject', true);
        }
        $project->update($validator->validated());

        return redirect()->route('project.show', [$project]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Project $project)
    {
        $project->delete();
        return redirect()->route('project.index');
    }
}

resources/views/project/index.blade.php
<x-layout>
    <div @if(session('createProject')) x-data="{createProject: true}" @else x-data="{createProject: false}" @endif>
        <x-menu scope="projects"/>
        <div class="grid grid-cols-5">
            <div class="col-span-4 h-screen overflow-scroll">
                <div class="bg-white row-span-1 p-4 sticky top-0">
                    <x-breadcrumb class="font-bold"/>
                </div>
                <div class="row-span-2">
                    <div x-show="!createProject" class="grid gap-4 grid-cols-5 p-4">
                        @foreach ($projects as $project)
                            <div class="text-{{$project->getStatusColor($project)}} border-2 border-{{$project->getStatusColor($project)}}
                                    bg-white grid gap-4 p-4 text-center rounded-lg">
                                <div class="font-bold">{{ $project->title }}</div>
                                <div class="bg-gray-100 rounded-lg h-4">
                                    <div class="bg-green-600 h-4 rounded-lg text-white" style="width: {{ $project->getProgress() }}%">
                                        <span class="text-xs">{{ $project->getProgress() }}%</span>
                                    </div>
                                </div>
                                <div class="">{{$project->formatDeadline()}}</div>
                                <a href="{{ route('project.show', [$project]) }}"
                                    class="bg-{{$project->getStatusColor($project)}} px-2 py-1 rounded text-white hover:opacity-80">
                                    Anzeigen
                                </a>
                            </div>
                        @endforeach
                    </div>
                    <div x-show="createProject" class="w-full">
                        <form class="grid gap-4" method="POST" action="{{route('project.store')}}">
                            @csrf
                            <x-input label="Titel*" name="title" type="text"/>
                            <x-input label="Kosten*" name="costs" type="textarea"/>
                            <x-input label="Nutzen*" name="benefit" type="textarea"/>
                            <x-input label="Umfang*" name="scope" type="textarea"/>
                            <x-input label="Qualität*" name="quality" type="textarea"/>
                            <x-input label="Risiko*" name="risk" type="textarea"/>
                            <x-input label="Interessengruppen" name="groups" type="textarea"/>
                            <x-input label="Deadline*" name="deadline" type="date"/>
                            <x-input label="Erstellen" name="erstellen" type="submit"/>
                        </form>
                        <div class="grid grid-cols-8">
                            <button x-on:click="createProject = false"
                                class="border border-black rounded-full hover:bg-black hover:text-white hover:cursor-pointer col-span-3 col-start-4 p-1">
                                Abbrechen
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-span-1 bg-gray-100 h-screen">
                <div class="">
                    <div class="p-4">Aktivitäten</div>
                </div>
            </div>
        </div>
    </div>
</x-layout>

resources/views/project/show.blade.php
<x-layout>
    <div @if(session('editProject')) x-data="{editProject: true}" @elseif(session('createPackage')) x-data="{createPackage: true}" @else x-data="{editProject: false, createPackage: false}" @endif class="">
        <x-menu scope="packages" :model="$project"/>
        <div class="grid grid-cols-5">
            <div class="col-span-3 h-screen overflow-scroll">
                <div class="p-4 sticky top-0 bg-white">
                    <x-breadcrumb />
                    <x-breadcrumb url="{{ route('project.show', [$project]) }}" name="{{ $project->title }}" class="font-bold"/>
                </div>
                <div x-show="!editProject && !createPackage" class="grid gap-4 grid-cols-3 p-4">
                    @foreach ($packages->sortBy('deadline')->sortByDesc('status') as $package)
                        <div class="text-{{$package->getStatusColor($package)}} border-2 border-{{$package->getStatusColor($package)}} bg-white p-4 grid gap-2 text-center rounded-lg">
                            <div class="font-bold">{{ $package->title }}</div>
                            <div class="">{{ $package->shortDescription }}</div>
                            <div class="">{{ $package->duration }}</div>
                            <div class="">{{ $package->deadline }}</div>
                            <a href="{{ route('package.show', [$package]) }}"
                                class="bg-{{$package->getStatusColor($package)}} px-2 py-1 rounded text-white hover:opacity-80">
                                Anzeigen
                            </a>
                        </div>
                    @endforeach
                </div>
                <div x-show="editProject" class="w-full">
                    <form class="grid gap-4 p-4" method="POST" action="{{route('project.update', [$project])}}">
                        @csrf
                        @method('PATCH')
                        <x-input label="Titel*" name="title" type="text" :model="$project"/>
                        <x-input label="Status*" name="status" type="select" options="Offen,Fertig,Abgebrochen" :model="$project"/>
                        <x-input label="Kosten*" name="costs" type="textarea" :model="$project"/>
                        <x-input label="Nutzen*" name="benefit" type="textarea" :model="$project"/>
                        <x-input label="Umfang*" name="scope" type="textarea" :model="$project"/>
                        <x-input label="Qualität*" name="quality" type="textarea" :model="$project"/>
                        <x-input label="Risiko*" name="risk" type="textarea" :model="$project"/>
                        <x-input label="Interessengruppen" name="groups" type="textarea" :model="$project"/>
                        <x-input label="Deadline*" name="deadline" type="date" :model="$project"/>
                        <x-input label="Speichern" name="speichern" type="submit"/>
                    </form>
                    <div class="grid grid-cols-8 px-4">
                        <button x-on:click="editProject = false"
                            class="border border-black rounded-full hover:bg-black hover:text-white hover:cursor-pointer col-span-3 col-start-4 p-1">
                            Abbrechen
                        </button>
                    </div>
                </div>
                <div x-show="createPackage" class="w-full">
                    <form class="grid gap-4 p-4" method="POST" action="{{route('package.store')}}">
                        @csrf
                        <x-input label="Titel*" name="title" type="text"/>
                        <x-input label="Zuweisung*" name="assigment" type="text"/>
                        <x-input label="Status" name="status" type="select" options="Offen,Fertig"/>
                        <x-input label="Duration" name="duration" type="select" options="~Stunde,~Tag,~Woche"/>
                        <x-input label="Kurze Beschreibung" name="shortDescription" type="textarea"/>
                        <x-input label="Beschreibung" name="description" type="textarea"/>
                        <x-input label="Deadline*" name="deadline" type="date"/>
                        <input type="hidden" name="project_id" value="{{$project->id}}">
                        <x-input label="Erstellen" name="erstellen" type="submit"/>
                    </form>
                    <div class="grid grid-cols-8 px-4">
                        <button x-on:click="createPackage = false"
                            class="border border-black rounded-full hover:bg-black hover:text-white hover:cursor-pointer col-span-3 col-start-4 p-1">
                            Abbrechen
                        </button>
                    </div>
                </div>
            </div>
            <div class="bg-gray-100 col-span-2 h-screen">
                <div class="p-4 grid gap-4">
                    <h1 class="text-2xl text-center font-black">Projekt</h1>
                    <x-stats title="Titel" content="{{$project->title}}"/>
                    <x-stats title="Fortschritt" content="{{$project->getProgress($project)}}%"/>
                    <x-stats title="Nutzen" content="{{$project->benefit}}"/>
                    <x-stats title="Deadline" content="{{$project->formatDeadline()}}"/>
                    <x-stats title="Umfang" content="{{$project->scope}}"/>
                    <x-stats title="Qualität" content="{{$project->quality}}"/>
                    <x-stats title="Risiko" content="{{$project->risk}}"/>
                    <x-stats title="Interessengruppen" content="{{$project->interest_group}}"/>
                    <x-stats title="Status" content="{{$project->status}}"/>
                </div>
            </div>
        </div>
    </div>
</x-layout>