routes/web.php
<?php

use App\Http\Controllers\PackageController;
use App\Http\Controllers\ProjectController;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return redirect()->route('project.index');
});

Route::resource('project', ProjectController::class);
Route::resource('package', PackageController::class);

app/Models/Package.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Project;

class Package extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'assigment', 'duration', 'shortDescription', 'description', 'deadline', 'project_id', 'status'];

    public function project(){
        return $this->belongsTo(Project::class);
    }

    public function getStatusColor(Package $package){
        switch($package->status){
            case('Offen'): return 'black'; break;
            case('Fertig'): return 'green-600'; break;
        }
    }
}

app/Http/Controllers/PackageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePackageRequest;
use App\Http\Requests\UpdatePackageRequest;
use App\Models\Package;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class PackageController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'project_id' => 'required',
            'assigment' => 'required',
            'duration' => 'required',
            'shortDescription' => 'nullable',
            'description' => 'nullable',
            'deadline' => 'required|date'
        ]);

        if($validator->fails()){
            redirect()->route('package.index')->withErrors($validator)->with('createPackage', true);
        }

        $package = Package::create($validator->validated());

        return redirect()->route('package.show', [$package]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Package $package)
    {
        return view('package.show')->with('package', $package)->with('project', $package->project()->first());
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Package $package)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Package $package)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'status' => 'required',
            'project_id' => 'required',
            'assigment' => 'required',
            'duration' => 'required',
            'shortDescription' => 'nullable',
            'description' => 'nullable',
            'deadline' => 'required|date'
        ]);

        if($validator->fails()){
            redirect()->route('package.show', [$package])->withErrors($validator)->with('editPackage', true);
        }
        $package->update($validator->validated());

        return redirect()->route('package.show', [$package]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Package $package)
    {
        $project = $package->project()->first();
        $package->delete();
        return redirect()->route('project.show', [$project]);
    }
}

resources/views/package/show.blade.php
<x-layout>
    <div @if(session('editPackage')) x-data="{editPackage: true}" @else x-data="{editPackage: false}" @endif class="">
        <x-menu scope="package" :model="$package"/>
        <div class="grid grid-cols-5">
            <div class="col-span-3 h-screen overflow-scroll">
                <div class="bg-white row-span-1 p-4 sticky top-0">
                    <x-breadcrumb />
                    <x-breadcrumb url="{{ route('project.show', [$project]) }}" name="{{ $project->title }}"/>
                    <x-breadcrumb url="{{ route('package.show', [$package]) }}" name="{{ $package->title }}" class="font-bold"/>
                </div>
                <div class="row-span-2">
                    <div x-show="!editPackage" class="grid gap-4 grid-cols-5 p-4">
                        Kommentare
                    </div>
                </div>
                <div x-show="editPackage" class="w-full">
                    <form class="grid gap-4 p-4" method="POST" action="{{route('package.update', [$package])}}">
                        @csrf
                        @method('PATCH')
                        <x-input label="Titel*" name="title" type="text" :model="$package"/>
                        <x-input label="Zuweisung*" name="assigment" type="text" :model="$package"/>
                        <x-input label="Status" name="status" type="select" options="Offen,Fertig"/>
                        <x-input label="Dauer" name="duration" type="select" options="~Stunde,~Tag,~Woche" :model="$package"/>
                        <input type="hidden" name="project_id" value="{{$project->id}}">
                        <x-input label="Kurze Beschreibung" name="shortDescription" type="textarea" :model="$package"/>
                        <x-input label="Beschreibung" name="description" type="textarea" :model="$package"/>
                        <x-input label="Deadline*" name="deadline" type="date" :model="$package"/>
                        <x-input label="Speichern" name="speichern" type="submit"/>
                    </form>
                    <div class="grid grid-cols-8 px-4">
                        <button x-on:click="editPackage = false"
                            class="border border-black rounded-full hover:bg-black hover:text-white hover:cursor-pointer col-span-3 col-start-4 p-1">
                            Abbrechen
                        </button>
                    </div>
                </div>
            </div>
            <div class="bg-gray-100 col-span-2 h-screen">
                <div class="p-4 grid gap-4">
                    <h1 class="text-2xl text-center font-black">Arbeitspaket</h1>
                    <x-stats title="Titel" content="{{$package->title}}"/>
                    <x-stats title="Status" content="{{$package->status}}"/>
                    <x-stats title="Dauer" content="{{$package->duration}}"/>
                    <x-stats title="Kurze Beschreibung" content="{{$package->shortDescription}}"/>
                    <x-stats title="Beschreibung" content="{{$package->description}}"/>
                    <x-stats title="Zuweisung" content="{{$package->assigment}}"/>
                    <x-stats title="Deadline" content="{{$package->deadline}}"/>
                </div>
            </div>
        </div>
    </div>
</x-layout>